### ISSUE TITLE
Mixin conflict with SpiceOfFabric

### ISSUE THREAD

**Issue by No3371** [Globox1997/SpoiledZ#2]
```
[23:37:37] [main/WARN]: @Redirect conflict. Skipping spiceoffabric.mixins.json:MixinCakeBlock from mod spiceoffabric->@Redirect::eat(Lnet/minecraft/class_1702;IFLnet/minecraft/class_1936;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_1657;)V with priority 1000, already redirected by capsaicin.mixins.json:MixinCakeBlock from mod capsaicin->@Redirect::eat(Lnet/minecraft/class_1702;IF)V with priority 1000
[23:37:37] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.14.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.mehvahdjukaar.moonlight.api.fluids.FoodProvider.<clinit>(FoodProvider.java:33) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.SoftFluid$Builder.<init>(SoftFluid.java:244) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.fabric.SoftFluidRegistryImpl.getDefaultValue(SoftFluidRegistryImpl.java:81) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2272 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.14.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:21) ~[server-intermediary.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.FoodProvider.<clinit>(FoodProvider.java:33) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.SoftFluid$Builder.<init>(SoftFluid.java:244) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.fabric.SoftFluidRegistryImpl.getDefaultValue(SoftFluidRegistryImpl.java:81) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.14.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:21) ~[server-intermediary.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.FoodProvider.<clinit>(FoodProvider.java:33) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.SoftFluid$Builder.<init>(SoftFluid.java:244) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.fabric.SoftFluidRegistryImpl.getDefaultValue(SoftFluidRegistryImpl.java:81) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector eat(Lnet/minecraft/class_1702;IFLnet/minecraft/class_1936;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_1657;)V in spiceoffabric.mixins.json:MixinCakeBlock from mod spiceoffabric failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap spiceoffabric-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.14.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:21) ~[server-intermediary.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.FoodProvider.<clinit>(FoodProvider.java:33) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.SoftFluid$Builder.<init>(SoftFluid.java:244) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.fabric.SoftFluidRegistryImpl.getDefaultValue(SoftFluidRegistryImpl.java:81) ~[moonlight-1.19.2-2.2.13-fabric.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	... 3 more
```

**Comment by Globox1997** [comment]
Looks like an incompatibility with moon light lib but that might be fixed with the latest version
