### ISSUE TITLE
crashing while eating

### ISSUE THREAD

**Issue by dull4h4n** [Globox1997/SpoiledZ#4]
Had a few crashes, happens when I try to eat. Capcaisin said to be cause.

```
Caused by: java.lang.NullPointerException: Cannot invoke "de.siphalor.capsaicin.api.food.FoodContext.stack()" because "context" is null
	at net.spoiledz.init.EventInit.lambda$init$1(EventInit.java:35) ~[spoiledz-1.0.4.jar:?]
	at de.siphalor.capsaicin.impl.modifier.UniqueModifiers.apply(UniqueModifiers.java:33) ~[capsaicin-1.1.0+mc1.19.3-42f811c95307a55a.jar:?]
	at de.siphalor.capsaicin.impl.food.GenericFoodHandler.getFoodProperties(GenericFoodHandler.java:63) ~[capsaicin-1.1.0+mc1.19.3-42f811c95307a55a.jar:?]
	at de.siphalor.capsaicin.impl.food.GenericFoodHandler.getFoodComponent(GenericFoodHandler.java:39) ~[capsaicin-1.1.0+mc1.19.3-42f811c95307a55a.jar:?]
	at net.minecraft.class_1792.handler$zkk000$capsaicin$onGetFoodComponent(class_1792.java:1052) ~[client-intermediary.jar:?]
	at net.minecraft.class_1792.method_19264(class_1792.java:450) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_22382(class_1309.java:2990) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_37119(class_1309.java:2980) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6076(class_1309.java:2971) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2347) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_5773(class_746.java:229) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18646(class_638.java:267) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:466) ~[client-intermediary.jar:?]
	... 11 more

```

**Comment by Globox1997** [comment]
This should be fixed with the latest version.

**Comment by Derpford** [comment]
Got a similar crash on v1.0.7 for 1.19.2:
https://gist.github.com/Derpford/2f648ad6f15546e2f934e453ead636e9
